# Generated by Django 2.0.2 on 2018-02-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='upvote',
            field=models.NullBooleanField(),
        ),
    ]
